#pragma once

#ifdef RGB_MATRIX_ENABLE
#define RGB_DISABLE_TIMEOUT 15 * 60 * 1000 // 15 minutes
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CYCLE_PINWHEEL
#define RGB_MATRIX_STARTUP_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_STARTUP_SAT 100
#endif

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
